import { ISeat } from "../utils/interfaces"

export const seatList: ISeat[] = [
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 105,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 106,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 107,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 108,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 109,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 110,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 111,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 112,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 113,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 114,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 115,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 116,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 117,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 118,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "A",
        seatNumber: 119,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 105,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 106,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 107,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 108,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 109,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 110,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 111,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 112,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 113,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 114,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 115,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_4",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 116,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_1",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 117,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_2",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 118,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_3",
        eventId: "eventId_test",
        floor: 1,
        section: "TierA",
        row: "B",
        seatNumber: 119,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_5",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_6",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_7",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_8",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_9",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 105,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_10",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 106,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 107,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 108,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 109,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 110,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 111,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 112,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 113,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 114,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 115,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 116,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 117,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 118,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 119,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 120,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 121,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 122,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 123,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 124,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 125,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 126,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 127,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 128,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 129,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 130,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 131,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 132,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 133,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 134,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 135,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 136,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 137,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 138,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 139,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 140,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 141,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 142,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 143,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 144,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 145,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 146,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "TierC",
        row: "A",
        seatNumber: 147,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "RightWing",
        row: "",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "RightWing",
        row: "",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "RightWing",
        row: "",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "RightWing",
        row: "",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "LeftWing",
        row: "",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "LeftWing",
        row: "",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "LeftWing",
        row: "",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 2,
        section: "LeftWing",
        row: "",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "RightWing",
        row: "",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "RightWing",
        row: "",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "RightWing",
        row: "",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "RightWing",
        row: "",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "LeftWing",
        row: "",
        seatNumber: 101,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "LeftWing",
        row: "",
        seatNumber: 102,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "LeftWing",
        row: "",
        seatNumber: 103,
        available: true,
        inPlay: true,
    },
    {
        _id: "seatId_11",
        eventId: "eventId_test",
        floor: 3,
        section: "LeftWing",
        row: "",
        seatNumber: 104,
        available: true,
        inPlay: true,
    },
]